name: Deploy rules to prod project

on:
  create:
    tags:
      - v*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci
        env:
          CI: true

      - name: Test
        run: npm test

      - name: Deploy
        run: |
          npm install firebase-tools
          npm run deploy -- --token=${{ secrets.FIREBASE_TOKEN }} -P prod
