name: Deploy rules to prod project

on:
  push:
    tags:
      - v*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/iron

      - name: Install dependencies
        run: npm ci
        env:
          CI: true

      - name: Test
        run: npm test

      - name: Deploy
        run: |
          npm install firebase-tools
          npm run deploy -- --token=${{ secrets.FIREBASE_TOKEN }} -P prod
