name: Run tests

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/gallium

      - name: Install dependencies
        run: npm ci
        env:
          CI: true

      - name: Test
        run: npm test
        env:
          CI: true
